"""Type error examples and strong typing tests (Reference Manual §11.3)."""

from pathlib import Path

import pytest

from src.cpp_transpiler import transpile_to_cpp
from src.parser import parse_protel
from src.type_checker import TypeCheckError

ROOT = Path(__file__).resolve().parent.parent
ERRORS = ROOT / "examples" / "errors"


def _read(name: str) -> str:
    return (ERRORS / name).read_text(encoding="utf-8")


@pytest.mark.parametrize(
    "filename,message_fragment",
    [
        ("err_assign_integer_to_char.protel", "cannot assign integer to char"),
        (
            "err_assign_integer_to_packed_byte.protel",
            "packed byte-sized type",
        ),
        ("err_assign_integer_to_bool.protel", "cannot assign"),
        ("err_constant_out_of_range.protel", "out of range"),
        ("err_assign_incompatible_pointer.protel", "cannot assign"),
        ("err_return_type_mismatch.protel", "RETURN type"),
    ],
)
def test_error_examples_fail_type_check(filename: str, message_fragment: str):
    source = _read(filename)
    tree = parse_protel(source)
    with pytest.raises(TypeCheckError, match=message_fragment):
        transpile_to_cpp(tree, source_name=filename)


def test_ok_char_literal_transpiles():
    source = _read("ok_assign_char_literal.protel")
    tree = parse_protel(source)
    cpp = transpile_to_cpp(tree, source_name="ok_assign_char_literal.protel")
    assert "Generated by PROTEL" in cpp


def test_protel_driver_reports_type_error():
    import subprocess

    result = subprocess.run(
        [
            str(ROOT / ".venv" / "bin" / "python"),
            str(ROOT / "protel"),
            str(ERRORS / "err_assign_integer_to_char.protel"),
            "--parse-only",
        ],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    assert result.returncode == 0

    result = subprocess.run(
        [
            str(ROOT / ".venv" / "bin" / "python"),
            str(ROOT / "protel"),
            str(ERRORS / "err_assign_integer_to_char.protel"),
        ],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    assert result.returncode == 1
    assert "protel: type error" in result.stderr
    assert "cannot assign integer to char" in result.stderr