/* Generated by PROTEL 2026 C++ transpiler */
/* Source: /Users/vincente/PROTEL/examples/ref_oo_class_with_var.protel */
#include <cstdint>
#include <iostream>
#include "protel_io.hpp"

namespace protel_generated {
namespace oo_class_demo {
    /* FAST INTERFACE */

    /* TYPE integer */
    using integer = int16_t;

    /* TYPE class_with_var */
    class class_with_var {
    public:
        static int16_t class_var;
        int16_t instance_var;
        static void class_method(int16_t parameter);
        void instance_method(int16_t value);
    };


    /* IN class_with_var */

    int16_t class_with_var::class_var = 0;

    void class_with_var::class_method(int16_t parameter)
    {
        class_with_var::class_var = 5;
    }

    void class_with_var::instance_method(int16_t value)
    {
        this->instance_var = value;
    }

}  // namespace oo_class_demo

}  // namespace protel_generated

