"""PROTEL 2026 to C++ transpiler (namespaces, classes, this)."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from . import ast_nodes as ast
from .transpiler import CTranspiler, TranspileError

_CPP_RESERVED_TYPE_NAMES = frozenset({
    "bool", "char", "double", "float", "int", "long", "short", "void",
})

_LIBC_EXTERNAL_HEADERS: dict[str, str] = {
    "printf": "<cstdio>",
    "atoi": "<cstdlib>",
}


@dataclass(frozen=True)
class _EntryPointInfo:
    namespace: str
    name: str
    parms: list[tuple[list[str], Any, bool]]
    return_type: Any | None
    returns_integer: bool
    unix_argv: bool


def _sanitize_namespace(name: str) -> str:
    out = []
    for ch in name:
        if ch.isalnum() or ch == "_":
            out.append(ch)
        else:
            out.append("_")
    if not out or out[0].isdigit():
        out.insert(0, "_")
    return "".join(out)


class CppTranspiler(CTranspiler):
    def __init__(self, *, classical: bool = False, source_name: str = "input.P"):
        super().__init__(classical=classical, source_name=source_name)
        self._cpp = True
        self._current_namespace: str | None = None
        self._namespace_stack: list[str] = []
        self._entry_point: _EntryPointInfo | None = None
        self._section_class_bodies: list[tuple[str, ast.ClassType]] = []
        self._section_method_impls: list[
            tuple[str, ast.MethodImplDecl, ast.MethodDecl | None]
        ] = []
        self._external_procs: list[ast.ProcDecl] = []

    def transpile(self, compilation_unit: list[ast.Section]) -> str:
        self.lines = []
        self._method_impls = []
        self._class_methods = {}
        self._class_vars = {}
        self._var_types = {}
        self._entry_point = None
        self._section_class_bodies = []
        self._section_method_impls = []
        self._external_procs = []

        self._section_by_name = {section.name: section for section in compilation_unit}
        self._entry_point = self._resolve_entry_point(compilation_unit)
        self._exported_procs = self._resolve_exported_procedures(compilation_unit)
        self._exported_body_names = {proc.name for proc in self._exported_procs}

        self.emit("/* Generated by PROTEL 2026 C++ transpiler */")
        self.emit(f"/* Source: {self.source_name} */")
        self.emit("/* EXTERNAL C linkage for I/O; minimal runtime (protel_io.c). */")
        self.emit('#include <cstdint>')

        self._collect_external_procs(compilation_unit)
        libc_headers = sorted(
            {
                _LIBC_EXTERNAL_HEADERS[proc.name]
                for proc in self._external_procs
                if proc.name in _LIBC_EXTERNAL_HEADERS
            }
        )
        for header in libc_headers:
            self.emit(f"#include {header}")
        self.emit("")

        declared_externals = [
            proc
            for proc in self._external_procs
            if proc.name not in _LIBC_EXTERNAL_HEADERS
        ]
        if declared_externals:
            self.emit('extern "C" {')
            self.indent += 1
            for proc in declared_externals:
                self.emit(f"{self._cpp_external_proc_signature(proc)};")
            self.indent -= 1
            self.emit("}")
            self.emit("")

        self.emit("namespace protel_generated {")

        for section in compilation_unit:
            self._emit_cpp_section(section)

        self.emit("}  // namespace protel_generated")
        self.emit("")

        if self._exported_procs:
            self.emit('extern "C" {')
            self.indent += 1
            for proc in self._exported_procs:
                self._emit_cpp_exported_procedure(proc)
            self.indent -= 1
            self.emit("}")
            self.emit("")

        if self._entry_point:
            self._emit_cpp_main_wrapper(self._entry_point)

        return "\n".join(self.lines) + "\n"

    def _emit_cpp_main_wrapper(self, entry: _EntryPointInfo) -> None:
        ns, name = entry.namespace, entry.name
        call = f"protel_generated::{ns}::{name}"
        if entry.unix_argv:
            self.emit("int main(int argc, char** argv) {")
            self.indent += 1
            if entry.returns_integer:
                self.emit(f"return {call}(argc, argv);")
            else:
                self.emit(f"{call}(argc, argv);")
                self.emit("return 0;")
        else:
            self.emit("int main() {")
            self.indent += 1
            if entry.returns_integer:
                self.emit(f"return {call}();")
            else:
                self.emit(f"{call}();")
                self.emit("return 0;")
        self.indent -= 1
        self.emit("}")
        self.emit("")

    def _resolve_entry_point(
        self, compilation_unit: list[ast.Section]
    ) -> _EntryPointInfo | None:
        entries: list[tuple[ast.Section, ast.ProcDecl]] = []
        for section in compilation_unit:
            for decl in section.declarations:
                if isinstance(decl, ast.ProcDecl) and decl.entry:
                    entries.append((section, decl))

        if not entries:
            return None
        if len(entries) > 1:
            names = ", ".join(decl.name for _, decl in entries)
            raise TranspileError(
                f"multiple ENTRY procedures ({names}); only one ENTRY per module"
            )

        entry_section, entry_decl = entries[0]
        if entry_decl.return_type or entry_decl.body:
            raise TranspileError(
                f"ENTRY procedure {entry_decl.name!r} must be declared as "
                f"PROC[(argc integer, argv PTR TO PTR TO char)] IS ENTRY or PROC() IS ENTRY"
            )

        body_section: ast.Section | None = None
        body_decl: ast.ProcDecl | None = None
        for section in compilation_unit:
            for decl in section.declarations:
                if (
                    isinstance(decl, ast.ProcDecl)
                    and decl.name == entry_decl.name
                    and decl.body is not None
                    and not decl.entry
                ):
                    if body_decl is not None:
                        raise TranspileError(
                            f"duplicate body for ENTRY procedure {entry_decl.name!r}"
                        )
                    body_section = section
                    body_decl = decl

        if body_decl is None:
            raise TranspileError(
                f"ENTRY procedure {entry_decl.name!r} has no procedure body in this module"
            )
        if not self._entry_parm_lists_match(entry_decl.parms, body_decl.parms):
            raise TranspileError(
                f"ENTRY procedure {entry_decl.name!r} declaration parameters must "
                f"match the procedure body signature"
            )
        if body_decl.return_type is not None and not self._is_integer_return_type(
            body_decl.return_type
        ):
            raise TranspileError(
                f"ENTRY procedure {entry_decl.name!r} may RETURNS integer only "
                f"(shell exit status)"
            )
        unix_argv = self._is_unix_argv_entry_parms(entry_decl.parms)
        if entry_decl.parms and not unix_argv:
            raise TranspileError(
                f"ENTRY procedure {entry_decl.name!r} parameters must be "
                f"(argc integer, argv PTR TO PTR TO char) for UNIX command-line hosts"
            )
        if body_section is not entry_section:
            raise TranspileError(
                f"ENTRY procedure {entry_decl.name!r} must be declared and defined "
                f"in the same section ({entry_section.name!r})"
            )

        returns_integer = body_decl.return_type is not None
        return _EntryPointInfo(
            namespace=_sanitize_namespace(body_section.name),
            name=entry_decl.name,
            parms=entry_decl.parms,
            return_type=body_decl.return_type,
            returns_integer=returns_integer,
            unix_argv=unix_argv,
        )

    def _unwrap_entry_type(self, spec: Any) -> Any:
        from lark import Tree

        while isinstance(spec, Tree):
            if spec.children:
                spec = spec.children[0]
            else:
                break
        return spec

    def _is_integer_type(self, spec: Any) -> bool:
        spec = self._unwrap_entry_type(spec)
        if isinstance(spec, ast.DefinedType):
            return spec.name == "integer"
        if isinstance(spec, ast.RangeType):
            return True
        return False

    def _is_ptr_to_ptr_to_char(self, spec: Any) -> bool:
        spec = self._unwrap_entry_type(spec)
        if not isinstance(spec, ast.PtrType):
            return False
        target = self._unwrap_entry_type(spec.target)
        if not isinstance(target, ast.PtrType):
            return False
        inner = self._unwrap_entry_type(target.target)
        return isinstance(inner, ast.DefinedType) and inner.name == "char"

    def _is_unix_argv_entry_parms(
        self, parms: list[tuple[list[str], Any, bool]]
    ) -> bool:
        if len(parms) != 2:
            return False
        _, argc_type, _ = parms[0]
        _, argv_type, _ = parms[1]
        return self._is_integer_type(argc_type) and self._is_ptr_to_ptr_to_char(
            argv_type
        )

    def _entry_parm_lists_match(
        self,
        left: list[tuple[list[str], Any, bool]],
        right: list[tuple[list[str], Any, bool]],
    ) -> bool:
        if len(left) != len(right):
            return False
        for (_, left_type, left_ref), (_, right_type, right_ref) in zip(left, right):
            if left_ref != right_ref:
                return False
            if not self._entry_parm_types_equal(left_type, right_type):
                return False
        return True

    def _entry_parm_types_equal(self, left: Any, right: Any) -> bool:
        left = self._unwrap_entry_type(left)
        right = self._unwrap_entry_type(right)
        if type(left) is not type(right):
            return False
        if isinstance(left, ast.DefinedType):
            return left.name == right.name
        if isinstance(left, ast.PtrType):
            return self._entry_parm_types_equal(left.target, right.target)
        if isinstance(left, ast.RangeType):
            return (
                self._c_expr(left.low) == self._c_expr(right.low)
                and self._c_expr(left.high) == self._c_expr(right.high)
            )
        return left == right

    def _is_integer_return_type(self, spec: Any) -> bool:
        return self._is_integer_type(spec)

    def _resolve_exported_procedures(
        self, compilation_unit: list[ast.Section]
    ) -> list[ast.ProcDecl]:
        exports: dict[str, tuple[ast.Section, ast.ProcDecl]] = {}
        for section in compilation_unit:
            for decl in section.declarations:
                if isinstance(decl, ast.ProcDecl) and decl.export:
                    if decl.name in exports:
                        raise TranspileError(
                            f"duplicate EXPORT declaration for {decl.name!r}"
                        )
                    exports[decl.name] = (section, decl)

        if not exports:
            return []

        bodies: dict[str, ast.ProcDecl] = {}
        body_sections: dict[str, ast.Section] = {}
        for section in compilation_unit:
            for decl in section.declarations:
                if (
                    isinstance(decl, ast.ProcDecl)
                    and decl.name in exports
                    and decl.body is not None
                    and not decl.export
                ):
                    if decl.name in bodies:
                        raise TranspileError(
                            f"duplicate body for EXPORT procedure {decl.name!r}"
                        )
                    bodies[decl.name] = decl
                    body_sections[decl.name] = section

        resolved: list[ast.ProcDecl] = []
        for name, (export_section, export_decl) in exports.items():
            body = bodies.get(name)
            if body is None:
                raise TranspileError(
                    f"EXPORT procedure {name!r} has no procedure body in this module"
                )
            if body_sections[name] is not export_section:
                raise TranspileError(
                    f"EXPORT procedure {name!r} must be declared and defined "
                    f"in the same section ({export_section.name!r})"
                )
            if (
                body.parms != export_decl.parms
                or body.return_type != export_decl.return_type
                or body.pclass != export_decl.pclass
            ):
                raise TranspileError(
                    f"EXPORT declaration and body signatures differ for {name!r}"
                )
            resolved.append(body)
        return resolved

    def _emit_cpp_exported_procedure(self, proc: ast.ProcDecl):
        self.emit(self._cpp_proc_signature(proc))
        self.emit("{")
        self.indent += 1
        self._emit_block_body(proc.body)
        self.indent -= 1
        self.emit("}")
        self.emit("")

    def _collect_external_procs(self, compilation_unit: list[ast.Section]) -> None:
        self._external_procs = []
        for section in compilation_unit:
            for decl in section.declarations:
                if isinstance(decl, ast.ProcDecl) and decl.external:
                    self._external_procs.append(decl)

    def _embedded_module_names(self, section: ast.Section) -> list[str]:
        names: list[str] = []
        seen: set[str] = set()
        for module_name in (*section.of_modules, *section.uses_modules):
            if module_name not in seen:
                seen.add(module_name)
                names.append(module_name)
        return names

    def _emit_embedded_usings(self, section: ast.Section) -> None:
        for module_name in self._embedded_module_names(section):
            embedded_ns = _sanitize_namespace(module_name)
            embedded = self._section_by_name.get(module_name)
            if embedded is None:
                continue
            symbols: list[str] = []
            for decl in embedded.declarations:
                if isinstance(decl, ast.VarDecl):
                    symbols.extend(decl.names)
                elif isinstance(decl, ast.ProcDecl):
                    if (
                        decl.external
                        or decl.forward
                        or decl.entry
                        or decl.export
                        or decl.intrinsic
                    ):
                        continue
                    symbols.append(decl.name)
            for symbol in symbols:
                self.emit(f"using {embedded_ns}::{symbol};")
            if symbols:
                self.emit("")

    def _emit_cpp_section(self, section: ast.Section):
        ns = _sanitize_namespace(section.name)
        self._current_namespace = ns
        self._namespace_stack.append(ns)
        self._section_class_bodies = []
        self._section_method_impls = []
        self.emit(f"namespace {ns} {{")
        self.indent += 1
        self.emit(f"/* {section.module_type} {section.section_kind} */")
        if section.uses_modules:
            self.emit(f"/* USES: {', '.join(section.uses_modules)} */")
        if section.of_modules:
            self.emit(f"/* OF: {', '.join(section.of_modules)} */")
        self.emit("")

        self._emit_embedded_usings(section)

        for decl in section.declarations:
            self._emit_cpp_toplevel_decl(decl)
        for impl in section.class_impls:
            self._queue_class_impl(impl)
        for stmt in section.statements:
            self._emit_stmt(stmt)

        for class_name, spec in self._section_class_bodies:
            self._emit_cpp_class_definitions(class_name, spec)
        for class_name, impl, method_decl in self._section_method_impls:
            self._emit_cpp_method_impl(class_name, impl, method_decl)

        self.indent -= 1
        self.emit(f"}}  // namespace {ns}")
        self.emit("")
        self._namespace_stack.pop()
        self._current_namespace = self._namespace_stack[-1] if self._namespace_stack else None

    def _emit_cpp_toplevel_decl(self, decl):
        if isinstance(decl, ast.TypeDecl):
            self.types.declare(decl.names, decl.type_spec)
            for name in decl.names:
                self.emit(f"/* TYPE {name} */")
            if isinstance(decl.type_spec, ast.ClassType):
                self._emit_cpp_class_declaration(decl.names[0], decl.type_spec)
            elif isinstance(decl.type_spec, ast.StructType):
                self._emit_cpp_struct(decl.names[0], decl.type_spec)
            elif isinstance(decl.type_spec, ast.SymbolicRange):
                self._emit_symbolic_typedef(decl.names[0], decl.type_spec)
            else:
                for name in decl.names:
                    if name in _CPP_RESERVED_TYPE_NAMES:
                        self.emit(
                            f"/* TYPE {name} -> {self._cpp_type(decl.type_spec)} */"
                        )
                    else:
                        self.emit(f"using {name} = {self._cpp_type(decl.type_spec)};")
            self.emit("")
        elif isinstance(decl, ast.VarDecl):
            type_name = self._decl_type_name(decl.type_spec)
            for name in decl.names:
                if type_name:
                    self._var_types[name] = type_name
                line = f"{self._cpp_type_decl(decl.type_spec, name)}"
                if decl.init is not None:
                    line += f" = {self._c_init(decl.init)}"
                line += ";"
                self.emit(line)
            self.emit("")
        elif isinstance(decl, ast.ProcDecl):
            if decl.intrinsic:
                return
            if decl.forward:
                self.emit(f"/* FORWARD {decl.name} */")
                self.emit(self._cpp_proc_signature(decl) + ";")
                self.emit("")
                return
            if decl.external:
                self._external_procs.append(decl)
                return
            if decl.entry:
                self.emit(f"/* ENTRY {decl.name} */")
                forward = ast.ProcDecl(
                    name=decl.name,
                    parms=decl.parms,
                    return_type=(
                        self._entry_point.return_type
                        if self._entry_point is not None
                        and self._entry_point.name == decl.name
                        else None
                    ),
                    body=None,
                    pclass=decl.pclass,
                    entry=True,
                )
                self.emit(self._cpp_proc_signature(forward) + ";")
                self.emit("")
                return
            if decl.export:
                self.emit(f"/* EXPORT {decl.name} (defined with C linkage below) */")
                self.emit("")
                return
            if decl.body and decl.name in self._exported_body_names:
                return
            if decl.body:
                self._emit_cpp_procedure(decl)
            else:
                self.emit(self._cpp_proc_signature(decl) + ";")
                self.emit("")

    def _cpp_type(self, spec) -> str:
        spec = self._unwrap_type(spec)
        spec = self.types.resolve(spec)
        if isinstance(spec, ast.BoolType):
            return "bool"
        if isinstance(spec, ast.DefinedType) and spec.name in _CPP_RESERVED_TYPE_NAMES:
            resolved = self.types.resolve(spec)
            if resolved is not spec:
                return self._cpp_type(resolved)
        return self._c_type(spec)

    def _cpp_type_decl(self, spec, name: str) -> str:
        spec = self._unwrap_type(spec)
        if isinstance(spec, ast.TableType):
            elem = self._cpp_type(spec.element_type)
            count = self._table_count(spec.low, spec.high)
            return f"std::array<{elem}, {count}> {name}"
        return f"{self._cpp_type(spec)} {name}"

    def _emit_cpp_struct(self, name: str, spec: ast.StructType):
        self.types.declare([name], spec)
        self.emit(f"struct {name} {{")
        self.indent += 1
        for field_names, field_type in spec.fields:
            for field_name in field_names:
                self.emit(f"{self._cpp_type_decl(field_type, field_name)};")
        self.indent -= 1
        self.emit("};")

    def _emit_cpp_class_declaration(self, name: str, spec: ast.ClassType):
        self.types.declare([name], spec)
        method_map: dict[str, ast.MethodDecl] = {}
        class_vars: set[str] = set()
        self.emit(f"class {name} {{")
        self.emit("public:")
        self.indent += 1
        for part in spec.data_parts:
            if self._is_class_var_segment(part.access_attrs):
                for field_names, field_type in part.fields:
                    for field_name in field_names:
                        class_vars.add(field_name)
                        self.emit(f"static {self._cpp_type(field_type)} {field_name};")
                continue
            for field_names, field_type in part.fields:
                for field_name in field_names:
                    self.emit(f"{self._cpp_type_decl(field_type, field_name)};")
        for section in spec.operations:
            for method in section.methods:
                for method_name in method.names:
                    method_map[method_name] = method
                    self.emit(self._cpp_method_declaration(name, method_name, method) + ";")
        self.indent -= 1
        self.emit("};")
        self.emit("")
        self._class_vars[name] = class_vars
        self._class_methods[name] = method_map
        self._section_class_bodies.append((name, spec))

    def _emit_cpp_class_definitions(self, name: str, spec: ast.ClassType):
        for part in spec.data_parts:
            if not self._is_class_var_segment(part.access_attrs):
                continue
            for field_names, field_type in part.fields:
                for field_name in field_names:
                    self.emit(
                        f"{self._cpp_type(field_type)} {name}::{field_name} = 0;"
                    )
        self.emit("")

    def _cpp_method_declaration(self, class_name: str, method_name: str, method: ast.MethodDecl) -> str:
        ret = self._cpp_type(method.return_type) if method.return_type else "void"
        args = self._cpp_method_parm_list(class_name, method)
        if self._method_is_class_method(method):
            return f"static {ret} {method_name}({args})"
        return f"{ret} {method_name}({args})"

    def _cpp_method_parm_list(self, class_name: str, method: ast.MethodDecl) -> str:
        if self._method_is_class_method(method):
            return self._cpp_parm_list(method.parms)
        return self._cpp_parm_list(method.parms)

    def _cpp_parm_list(self, parms: list[tuple[list[str], Any, bool]]) -> str:
        if not parms:
            return ""
        parts: list[str] = []
        for names, type_spec, by_ref in parms:
            cpp_type = self._cpp_type(type_spec)
            for pname in names:
                if by_ref:
                    parts.append(f"{cpp_type}& {pname}")
                else:
                    parts.append(f"{cpp_type} {pname}")
        return ", ".join(parts)

    def _cpp_external_parm_type(self, type_spec) -> str:
        spec = self._unwrap_type(type_spec)
        if isinstance(spec, ast.PtrType):
            target = self._unwrap_type(spec.target)
            if isinstance(target, ast.DefinedType) and target.name == "char":
                return "const char*"
        return self._cpp_type(type_spec)

    def _cpp_external_parm_list(self, parms: list[tuple[list[str], Any, bool]]) -> str:
        if not parms:
            return ""
        parts: list[str] = []
        for names, type_spec, by_ref in parms:
            cpp_type = self._cpp_external_parm_type(type_spec)
            for pname in names:
                if by_ref:
                    parts.append(f"{cpp_type}& {pname}")
                else:
                    parts.append(f"{cpp_type} {pname}")
        return ", ".join(parts)

    def _cpp_external_proc_signature(self, proc: ast.ProcDecl) -> str:
        ret = self._cpp_type(proc.return_type) if proc.return_type else "void"
        args = self._cpp_external_parm_list(proc.parms)
        return f"{ret} {proc.name}({args})"

    def _cpp_proc_signature(self, proc: ast.ProcDecl) -> str:
        ret = self._cpp_type(proc.return_type) if proc.return_type else "void"
        args = self._cpp_parm_list(proc.parms)
        return f"{ret} {proc.name}({args})"

    def _emit_cpp_procedure(self, proc: ast.ProcDecl):
        self.emit(self._cpp_proc_signature(proc))
        self.emit("{")
        self.indent += 1
        self._emit_block_body(proc.body)
        self.indent -= 1
        self.emit("}")
        self.emit("")

    def _emit_cpp_method_impl(self, class_name: str, impl: ast.MethodImplDecl, method_decl: ast.MethodDecl | None):
        self._current_class = class_name
        is_class_method = method_decl is not None and self._method_is_class_method(method_decl)
        self._current_self = "this"
        if method_decl is not None:
            ret = self._cpp_type(method_decl.return_type) if method_decl.return_type else "void"
            args = self._cpp_method_parm_list(class_name, method_decl)
            self.emit(f"{ret} {class_name}::{impl.name}({args})")
        else:
            self.emit(f"void {class_name}::{impl.name}()")
        self.emit("{")
        self.indent += 1
        if is_class_method:
            pass
        self._emit_block_body(impl.body)
        self.indent -= 1
        self.emit("}")
        self.emit("")
        self._current_class = None
        self._current_self = "this"

    def _c_member_ref(self, expr: ast.MemberRef) -> str:
        if (
            isinstance(expr.base, ast.VarRef)
            and expr.base.is_self
            and self._current_class
            and expr.member in self._class_vars.get(self._current_class, set())
        ):
            return f"{self._current_class}::{expr.member}"
        if isinstance(expr.base, ast.VarRef) and expr.base.is_self:
            return f"this->{expr.member}"
        return f"{self._c_expr(expr.base)}.{expr.member}"

    def _c_expr(self, expr) -> str:
        if isinstance(expr, ast.MethodCall):
            args = ", ".join(self._c_expr(a) for a in expr.args)
            class_name = self._method_class_name(expr)
            if class_name and class_name in self._class_methods:
                method_decl = self._class_methods[class_name].get(expr.name)
                if method_decl is not None:
                    if self._method_is_class_method(method_decl):
                        return f"{class_name}::{expr.name}({args})"
                    receiver = self._c_expr(expr.receiver) if expr.receiver is not None else "this"
                    if args:
                        return f"{receiver}.{expr.name}({args})"
                    return f"{receiver}.{expr.name}()"
            if expr.receiver is not None:
                receiver = self._c_expr(expr.receiver)
                return f"{receiver}.{expr.name}({args})"
        return super()._c_expr(expr)

    def _method_call_args(self, call: ast.MethodCall, args: str) -> str:
        return args

    def _queue_class_impl(self, impl: ast.ClassImplSection):
        self.emit(f"/* IN {impl.class_name} */")
        method_map = self._class_methods.get(impl.class_name, {})
        for decl in impl.declarations:
            if isinstance(decl, ast.MethodImplDecl):
                method_decl = method_map.get(decl.name)
                self._section_method_impls.append((impl.class_name, decl, method_decl))
            else:
                self._emit_cpp_toplevel_decl(decl)
        for stmt in impl.statements:
            self._emit_stmt(stmt)
        self.emit("")

    def _method_class_name(self, call: ast.MethodCall) -> str | None:
        if isinstance(call.receiver, ast.VarRef):
            if call.receiver.name in self._var_types:
                return self._var_types[call.receiver.name]
            if call.receiver.name in self._class_methods:
                return call.receiver.name
        return super()._method_class_name(call)


def transpile_to_cpp(
    compilation_unit,
    *,
    classical: bool = False,
    source_name: str = "input.P",
    source_path: Path | None = None,
) -> str:
    from .module_resolver import resolve_compilation_unit
    from .type_checker import check_types

    if source_path is not None and not isinstance(source_path, Path):
        source_path = Path(source_path)
    compilation_unit = resolve_compilation_unit(
        compilation_unit,
        source_path=source_path,
        classical=classical,
    )
    check_types(compilation_unit, source_name=source_name)
    return CppTranspiler(classical=classical, source_name=source_name).transpile(
        compilation_unit
    )


def transpile_file_cpp(
    source: str,
    *,
    classical: bool = False,
    source_name: str = "input.P",
) -> str:
    from .parser import parse_protel

    tree = parse_protel(source, classical=classical)
    return transpile_to_cpp(tree, classical=classical, source_name=source_name)